version: "3"
services:
  app:
    container_name: notesapp-express
    restart: on-failure
    build: ./
    ports:
      - "80:80"
    volumes:
      - .:/app
    links:
      - mongodb
    command: npm run docker
  mongodb:
    container_name: mongo-for-notes-app
    image: mongo:latest
    ports:
      - "27017:27017"